<?php

use vBuilder\Utils\FileSystem;

?><h1>Translations (<?php echo htmlspecialchars(strtoupper($lang)); ?>)</h1>

<div class="tracy-inner tracy-DumpPanel vbuilder-TranslationPanel">
	<style>
		.vbuilder-missing-translation {
			color: #cc3300 !important; font-style: italic !important;
		}

		.vbuilder-saved-translation {
			color: #33bb33 !important;
		}
	</style>
	<table style="font-size: 0.9em; margin-right: 15px;">
		<?php foreach($translations as $key => $translation) : $formIndex = 0;?>
		<tr>
			<td style="min-width: 230px;"><div style="padding: 8px 0 5px 0; line-height: 11px;"><?php
				echo htmlspecialchars($translation['singular']);
				if(isset($translation['plural'])) { echo '<br />' . htmlspecialchars($translation['plural']); }
			?></div></td>
			<td<?php if(count($translation['hints']) == 0) : ?> style="padding-bottom: 5px;"<?php endif ?>><?php for($i = 0; $i < (isset($translation['plural']) ? count($pluralForm['plurals']) : 1); $i++) : ?><input type="text" class="form-control<?php if(!$translation['isTranslated']) echo ' vbuilder-missing-translation'; ?>" style="background: #fffdf3; padding: 5px; margin-top: 3px; font-size: 10px; line-height: 10px; height: auto; width: 200px;" <?php if(!$translation['isTranslated'] || !isset($translation['translations'][$i])) echo 'value="Missing" data-missing="true"'; else echo 'value="' . htmlspecialchars($translation['translations'][$i])  . '"'; ?> data-key="<?php echo htmlspecialchars($translation['singular']); ?>"  disabled="disabled" />
			<?php endfor;

				if(count($translation['hints'])) {
					echo "<p style=\"color: #666; font-size: 9px; margin-top: 10px;\">From:<br />";
					foreach(array_slice($translation['hints'], 0, 3) as $hint) {
						echo htmlspecialchars('./' . FileSystem::getRelativePath($basePath, $hint));
						echo "<br />";
					}

					if(count($translation['hints']) > 3) echo "<em>and " . (count($translation['hints']) - 3) . ' more</em>';
					echo "</p>";
				}
			?></td>
		</tr>
		<?php endforeach; ?>

		<tr style="background: none;">
			<td colspan="2" style="background: white; border-left: none; border-right: none;">&nbsp;</td>
		</tr>

		<?php foreach($dictionaries as $dictionary) : ?><tr>
			<td colspan="2">
				<?php echo htmlspecialchars('./' . FileSystem::getRelativePath($basePath, $dictionary['path'])); ?>
			</td>
		</tr><?php endforeach ?>
	</table>
	<script style="text/javascript">
		if (typeof jQuery != 'undefined') {

			// Requires jQuery >= 1.7.0
			var version = $.fn.jquery.split('.');
			if(parseInt(version[0]) > 1 || parseInt(version[1]) > 7) {

				var $panel = $('.vbuilder-TranslationPanel');
				$panel.find('INPUT').prop('disabled', false);

				$panel.on('focus', '.vbuilder-missing-translation', function () {
					$(this)
						.val('')
						.removeClass('vbuilder-missing-translation');
				});

				$panel.on('focus', 'INPUT[type=text]', function (event) {

						$(this).removeClass('vbuilder-saved-translation');

					}).on('keyup', 'INPUT[type=text]', function (event) {

						if(event.keyCode == 13) {
							$(this).blur();
						}
					});

				$panel.on('blur', 'INPUT[type=text]', function () {
					var $input = $(this)

					if($input.val() == '' && $input.data('missing'))
						$input.val('Missing').addClass('vbuilder-missing-translation');

					else {

						var values = [];
						$panel.find('INPUT[data-key="' + $input.data('key') + '"]').each(function () {
							values.push($(this).val());
						});

						var url = '<?php echo $actionUrl; ?>'; // Safe string
						var data = { 'translations': [] };
						data.translations[0] = {
							'key': $input.data('key'),
							'value': values
						};

						$.post(url, JSON.stringify(data), function (data, textStatus, jqXHR) {
							$input.addClass('vbuilder-saved-translation');

						}).fail(function () {
							alert('Error occured while saving translation.');
						});
					}
				});
			}
		}
	</script>
</div>