<?php

/**
 * This file is part of vBuilder Framework (vBuilder FW).
 * 
 * Copyright (c) 2011 Adam Staněk <adam.stanek@v3net.cz>
 * 
 * For more information visit http://www.vbuilder.cz
 * 
 * vBuilder FW is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * vBuilder FW is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with vBuilder FW. If not, see <http://www.gnu.org/licenses/>.
 */

namespace vBuilder\Orm\Behaviors;

use vBuilder,
	Nette,
	Nette\Application\ForbiddenRequestException,
	vBuilder\Orm\Entity;

/**
 * Behavior takes care of authorizing all entity actions against Nette\Security ACL
 * model. All resource ids are generated by ActiveEntity and all permission checking
 * is also taken care of internally.
 * 
 * ActiveEntity only.
 *
 * @author Adam Staněk (V3lbloud)
 * @since Apr 7, 2011
 */
class Secure implements vBuilder\Orm\IBehavior {
	
	const ACL_PERMISSION_READ = 'read';
	const ACL_PERMISSION_CREATE = 'create';
	const ACL_PERMISSION_UPDATE = 'update';
	const ACL_PERMISSION_DELETE = 'delete';
	
	/** @var reference to entity */
	private $entity;
	
	/** @var Nette\DI\IContainer DI */
	private $context;
	
	/** @var bool true if security checks are enabled */
	private $_isEnabled = true;
	
	/**
	 * Register behavior to entity
	 * 
	 * @param Nette\DI\IContainer DI
	 * @param ActiveEntity entity reference
	 * @param array of arguments (associative)
	 */
	public function __construct(Nette\DI\IContainer $context, Entity $entity, array $args = array()) {
		$this->entity = $entity;
		$this->context = $context;
		
		$this->entity->onFirstRead[] = \callback($this, 'readSecurityCheck');
		$this->entity->onCreate[] = \callback($this, 'createSecurityCheck');
		$this->entity->onUpdate[] = \callback($this, 'updateSecurityCheck');
		$this->entity->onPreDelete[] = \callback($this, 'deleteSecurityCheck');
	}
	
	/**
	 * Allow to bypass security check
	 * 
	 * @param bool 
	 */
	public function setBypassSecurityCheck($enabled = true) {
		$this->_isEnabled = !$enabled;
	}
	
	/**
	 * Returns true if security checks will be bypassed
	 * 
	 * @return bool 
	 */
	public function getBypassSecurityCheck() {
		return !$this->_isEnabled;
	}
	
	/**
	 * This function is called before first read of any data (except for ID fields).
	 * It takes care of checking for read permission.
	 * 
	 * @throws ForbiddenRequestException if user does not have permission to read this entity
	 */
	public function readSecurityCheck() {		
		$this->checkPermission(self::ACL_PERMISSION_READ);
	}
	
	/**
	 * This function is called before insert command is commited to DB
	 * 
	 * @throws ForbiddenRequestException if user does not have permission to create this entity
	 */
	public function createSecurityCheck() {
		$this->checkPermission(self::ACL_PERMISSION_CREATE);
	}
	
	/**
	 * This function is called before update command is commited to DB
	 * 
	 * @throws ForbiddenRequestException if user does not have permission to update this entity
	 */
	public function updateSecurityCheck() {
		$this->checkPermission(self::ACL_PERMISSION_UPDATE);
	}
	
	/**
	 * This function is called before delete command is commited to DB
	 * 
	 * @throws ForbiddenRequestException if user does not have permission to delete this entity
	 */
	public function deleteSecurityCheck() {
		$this->checkPermission(self::ACL_PERMISSION_DELETE);
	}
		
	/**
	 * Helper function for checking permission on current entity
	 * 
	 * @param string permission name
	 * @throws ForbiddenRequestException if user does not have permission to do that
	 */
	protected function checkPermission($permission) {
		if(!$this->_isEnabled) return ;		
		
		if(!$this->context->user->isAllowed($this->entity, $permission))
			throw new ForbiddenRequestException("Operation '$permission' is not permitted on '".$this->entity->getResourceId()."'");
	}
	
}
