<?php
use Nette\Diagnostics\Helpers;

$bs = vBuilder\Test\BlueScreen::getInstance();

?><!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="robots" content="noindex,noarchive">
	<meta name="generator" content="vBuilder Framework">

	<title>Test failed</title>

	<?php include __DIR__ . '/style.phtml'; ?>
</head>

<body>
	<div id="netteBluescreen">
		<div id="netteBluescreenError" class="panel">
			<h1>Test failed</h1>

			<p><?php echo $bs->getMessage(); ?></p>
		</div>
		
		<?php if($bs->getAssertActual() !== null || $bs->getAssertExpected() !== null) : ?>
			<div class="panel" style="margin-top: 20px;">
				<div class="inner">
					<table cellspacing="20" class="varCompTable">
						<tr>
							<td>
								<p><b>Expected:</b></b>
								<?php d($bs->getAssertExpected()); ?>
							</td>
							
							<td>
								<p><b>Actual:</b></b>
								<?php d($bs->getAssertActual()); ?>
							</td>
						</tr>
					</table>
				</div>
			</div>
		<?php endif ?>
		
		<div class="panel" style="margin-top: 20px;"> 
			<div class="inner">
				<p><b>File:</b> <?php echo Helpers::editorLink($bs->getFileBrowserFile(), $bs->getFileBrowserLine()); ?> &nbsp; <b>Line:</b> <?php echo intval($bs->getFileBrowserLine()); ?></p>
				<div class="fileContent">
					<?php echo nl2br(\Nette\Diagnostics\BlueScreen::highlightFile($bs->getFileBrowserFile(), $bs->getFileBrowserLine())); ?>
				</div>
			</div>
		</div>
	</div>
</body>
</html>