<style type="text/css">
	html {
		overflow-y: scroll;
	}

	body {
		margin: 0 0 2em;
		padding: 0;
	}

	#netteBluescreen {
		font: 9pt/1.5 Verdana, sans-serif;
		background: white;
		color: #333;
		position: absolute;
		left: 0;
		top: 0;
		width: 100%;
		z-index: 23178;
		text-align: left;
	}

	#netteBluescreen * {
		font: inherit;
		color: inherit;
		background: transparent;
		border: none;
		margin: 0;
		padding: 0;
		text-align: inherit;
		text-indent: 0;
	}

	#netteBluescreen b {
		font-weight: bold;
	}

	#netteBluescreen i {
		font-style: italic;
	}

	#netteBluescreen a {
		text-decoration: none;
		color: #328ADC;
		padding: 2px 4px;
		margin: -2px -4px;
	}

	#netteBluescreen a:hover, #netteBluescreen a:active, #netteBluescreen a:focus {
		color: #085AA3;
	}

	#netteBluescreen a abbr {
		font-family: sans-serif;
		color: #BBB;
	}

	#netteBluescreenError, #netteBluescreenSuccess {
		color: white;
		font: 13pt/1.5 Verdana, sans-serif !important;
		display: block;
	}
	
	#netteBluescreenError {
		background: #CD1818;
	}

	#netteBluescreenSuccess {
		background: #57c101;
	}
	
	#netteBluescreen h1 {
		font-size: 18pt;
		font-weight: normal;
		text-shadow: 1px 1px 0 rgba(0, 0, 0, .4);
		margin: .7em 0;
	}

	#netteBluescreen h2 {
		font: 14pt/1.5 sans-serif !important;
		color: #888;
		margin: .6em 0;
	}

	#netteBluescreen h3 {
		font: bold 10pt/1.5 Verdana, sans-serif !important;
		margin: 1em 0;
		padding: 0;
	}

	#netteBluescreen p, #netteBluescreen pre {
		margin: .8em 0
	}

	#netteBluescreen pre, #netteBluescreen .fileContent {
		background: #FDF5CE;
		padding: .4em .7em;
		border: 1px dotted silver;
		overflow: auto;
	}

	#netteBluescreen div.panel {
		padding: 1px 25px;
	}

	#netteBluescreen div.inner {
		background: #F4F3F1;
		padding: .1em 1em 1em;
		border-radius: 8px;
		-moz-border-radius: 8px;
		-webkit-border-radius: 8px;
	}

	#netteBluescreen  .fileContent {
		background: #fdf5ce;
		font: 9pt/1.5 Consolas, monospace !important;
	}

	#netteBluescreen  .fileContent .highlight {
		background: #CD1818;
		color: white;
		font-weight: bold;
		font-style: normal;
		display: block;
		padding: 0 .4em;
		margin: 0 -.4em;
	}

	#netteBluescreen .fileContent .line {
		color: #9F9C7F;
		font-weight: normal;
		font-style: normal;
	}
	
	#netteBluescreen .varCompTable pre {
		min-width: 200px;
	}
</style>
